// Types for respondent data
export interface Message {
  role: "agent" | "user"
  content: string
}

export interface Respondent {
  id: string
  name: string
  tagline: string
  demographics: {
    occupation?: string
    sport?: string
    experience?: string
    apps?: string[]
  }
  conversation: Message[]
  audioUrl: string
  keyInsights?: string[]
  accentColor: string
}

// Complete transcripts from CSV
export const respondents: Respondent[] = [
  {
    id: "01",
    name: "Faris",
    tagline: "Veteran softball player using Reclub & Kuy to find communities",
    demographics: {
      occupation: "Karyawan Swasta",
      sport: "Softball",
      experience: "5 tahun",
      apps: ["Reclub", "Kuy", "WhatsApp", "Instagram", "YouTube"],
    },
    accentColor: "from-orange-500 to-amber-600",
    conversation: [
      { role: "agent", content: "Halo" },
      { role: "user", content: "Halo." },
      { role: "agent", content: "Halo! Selamat pagi. Terima kasih sudah meluangkan waktu untuk bergabung dengan saya hari ini. Nama saya Putri, dan saya akan memandu diskusi kita tentang kebiasaan olahraga kamu. Santai aja ya, nggak ada jawaban benar atau salah—ini sekadar percakapan biasa. Boleh tahu nama kamu dan apa kesibukan sehari-hari kamu, misalnya pekerjaan atau aktivitas utama?" },
      { role: "user", content: "..." },
      { role: "agent", content: "Halo, masih ada nggak? Boleh kita mulai diskusinya?" },
      { role: "user", content: "Halo, halo." },
      { role: "agent", content: "Halo! Oke, senang mendengar kamu masih di sini. Jadi, bisa kita mulai? Boleh tahu nama kamu siapa dan apa yang biasanya kamu lakukan sehari-hari?" },
      { role: "user", content: "Sehari kerjaan pagi." },
      { role: "agent", content: "Ah oke, jadi kamu kerja pagi. Itu bagus. Tapi boleh tahu nama kamu siapa dulu?" },
      { role: "user", content: "..." },
      { role: "agent", content: "Halo, masih ada? Nama kamu siapa?" },
      { role: "user", content: "Halo nama saya Farid." },
      { role: "agent", content: "Ah, senang berkenalan dengan kamu, Farid! Terima kasih. Jadi kamu kerja pagi setiap hari, ya? Apa jenis pekerjaan kamu kalau boleh tahu?" },
      { role: "user", content: "Karyawan swasta." },
      { role: "agent", content: "Ah oke, karyawan swasta. Berarti jadwalnya cukup padat ya. Nah, sekarang saya pengin tahu tentang hobi olahraga kamu. Udah berapa lama kamu menjalani hobi olahraga ini, Farid?" },
      { role: "user", content: "Hobi olahraga?" },
      { role: "agent", content: "Iya, hobi olahraga kamu. Misalnya lari, badminton, futsal, atau olahraga apa pun yang kamu suka dan rutin dilakukan. Ada nggak?" },
      { role: "user", content: "Saya, saya mensof bo udah lima tahun." },
      { role: "agent", content: "Ah menarik! Jadi kamu main sofbol sudah lima tahun. Itu lama banget, Farid. Berarti kamu sudah cukup berpengalaman dong. Gimana cara kamu bisa nyeimpin waktu buat main sofbol di jadwal kerja pagi kamu yang padat?" },
      { role: "user", content: "Ah, orangnya sih tiap jam delapan sampai jam sepuluh malam jadi masih bisa pulang kerja." },
      { role: "agent", content: "Ah oke, jadi mainnya malam hari dari jam delapan sampai jam sepuluh. Itu pas banget setelah pulang kerja ya. Nah, dengan jadwal yang cukup ketat gitu, apakah ada hal lain yang terpaksa kamu korbankan atau kamu kurangi biar bisa tetap main sofbol?" },
      { role: "user", content: "Nggak deh sih, jatuh awas pas." },
      { role: "agent", content: "Ah oke, jadi semuanya jatuh pas dengan baik. Bagus sekali, Farid. Nah, sekarang saya pengin tahu tentang awal-awal kamu mulai main sofbol. Coba ingat-ingat dulu, apa momen atau pemicu yang bikin kamu mulai main sofbol pertama kali? Siapa atau apa yang menginspirasi kamu?" },
      { role: "user", content: "Saya udah main dari kecil tapi baru bisa main lagi pas umur segini karena ada teman-teman yang main." },
      { role: "agent", content: "Ah menarik! Jadi kamu sudah main sofbol dari kecil, tapi baru bisa main lagi sekarang karena ada teman-teman yang ajak. Berarti teman-teman itu yang jadi pemicu kamu untuk kembali main sofbol lagi ya?" },
      { role: "user", content: "Iya betul." },
      { role: "agent", content: "Ah oke, siap. Jadi waktu teman-teman kamu ajak main sofbol lagi, apa satu hal pertama banget yang kamu lakukan saat itu? Apa yang kamu beli atau siapa yang kamu kontak?" },
      { role: "user", content: "Alat-alat kayak glove, terus beli batnya juga, beli batting glove, terus ngajak temen-temen yang lama main." },
      { role: "agent", content: "Ah bagus, jadi kamu langsung persiapkan peralatan lengkap—glove, bat, batting glove. Terus kamu juga ngajak temen-temen yang dulu main bareng. Itu smart move, Farid. Nah, waktu fase awal itu, apakah kamu pakai aplikasi atau website tertentu buat cari informasi tentang sofbol atau cari tempat main?" },
      { role: "user", content: "Iya saya pakai namanya Re Club dan juga Kue." },
      { role: "agent", content: "Ah oke, jadi kamu pakai Reclub dan Kue. Menarik! Buat apa sih kamu pakai aplikasi-aplikasi itu? Apa untuk cari lapangan, cari teman main, atau apa?" },
      { role: "user", content: "Cari komunitas yang lagi ada latihan, jadi bisa join karena kalau main sendiri nggak bisa." },
      { role: "agent", content: "Ah oke, jadi kamu pakai Reclub dan Kue buat cari komunitas sofbol yang lagi ada latihan, terus kamu bisa join mereka. Karena memang sofbol butuh banyak orang ya, nggak bisa main sendiri. Nah, di minggu-minggu awal waktu kamu mulai join komunitas itu, apa tantangan atau kesulitan terbesar yang kamu hadapi? Misalnya susah adaptasi, susah cari teman, atau apa?" },
      { role: "user", content: "..." },
      { role: "agent", content: "Halo..." },
      { role: "user", content: "Jadwalnya sih yang cari yang cocok." },
      { role: "agent", content: "Ah oke, jadi tantangan utamanya adalah mencari jadwal yang cocok dengan jadwal kerja kamu. Itu memang ribet ya, apalagi kamu kerja pagi. Apakah akhirnya kamu ketemu jadwal yang pas atau masih sering ada konflik?" },
      { role: "user", content: "Yah kan masih usahain jadi jadwal yang kosong jadi mesti ngecek ke break club atau koi bolak balik mana yang lagi ada latihan." },
      { role: "agent", content: "Ah oke, jadi kamu harus bolak-balik ngecek di Reclub dan Kue untuk lihat mana yang ada latihan di jadwal kosong kamu. Itu memang agak ribet ya, tapi kamu tetap usaha. Nah sekarang kita bahas rutinitas kamu yang sekarang. Coba bayangkan sesi sofbol terakhir kamu, apa yang jadi pemicu kamu berangkat hari itu? Apakah jadwal rutin, notifikasi dari aplikasi, atau gimana?" },
      { role: "user", content: "Karena udah jadwal rutin dan emang lagi pengen latihan aja sih." },
      { role: "agent", content: "Ah oke, jadi kombinasi antara jadwal rutin dan keinginan untuk latihan. Siap. Nah, begitu kamu memutuskan \"Oke, gue berangkat latihan hari ini\", apa langkah pertama yang kamu ambil? Apakah buka aplikasi, kontak teman, atau apa?" },
      { role: "user", content: "Cek aplikasi Reclap dan Kui untuk booking dari hari sebelumnya." },
      { role: "agent", content: "Ah oke, jadi kamu sudah cek aplikasi Reclub dan Kui dari hari sebelumnya untuk booking lapangan. Itu berarti kamu planning ahead ya. Nah, gimana proses booking lapangannya sendiri? Ada drama atau frustrasi tertentu saat booking, atau lancar-lancar aja?" },
      { role: "user", content: "Kalo booking lapangan karena udah ada jadwal latihannya jadi join sama komunitas yang lagi latihan di jam tersebut sih." },
      { role: "agent", content: "Ah oke, jadi kamu nggak perlu booking lapangan sendiri karena kamu langsung join dengan komunitas yang udah punya jadwal latihan di jam itu. Jadi lebih praktis ya. Nah, pas kamu lagi main sofbol, fokus utama kamu apa sih? Apakah kejar performa, tracking stats, atau lebih sekadar have fun dan sosialisasi aja sama teman-teman?" },
      { role: "user", content: "Itu pengen sosialisasi, dua pengen ningkatin skill dan latihan yang banyak aja." },
      { role: "agent", content: "Ah menarik! Jadi ada dua hal yang kamu kejar—sosialisasi sama teman-teman, dan juga pengen ningkatin skill dengan latihan yang banyak. Dua-duanya penting buat kamu ya. Nah, pas lagi main sofbol, ada aplikasi yang nyala atau kamu pakai saat itu? Misalnya buat tracking, score keeper, atau apa?" },
      { role: "user", content: "Oke, untuk part three." },
      { role: "agent", content: "Ah oke, Farid. Jadi pas lagi main sofbol, ada aplikasi yang nyala atau kamu gunakan saat itu nggak? Misalnya buat tracking, score keeper, atau aplikasi lain?" },
      { role: "user", content: "Untuk, untuk tracking." },
      { role: "agent", content: "Ah oke, jadi kamu..." },
      { role: "user", content: "Oke, oke, jangan." },
      { role: "agent", content: "Ah ip, siap Farid. Nah, detik di mana kamu berhenti main sofbol, apa hal pertama yang kamu lakukan? Apakah cek stats, ambil foto, cari makan, atau apa?" },
      { role: "user", content: "Foto-foto dulu sih, terus habis itu pulangnya baru makan malam." },
      { role: "agent", content: "Ah oke, jadi kamu foto-foto dulu setelah selesai main, terus pulang dan makan malam. Bagus. Nah, dari semua proses tadi—mulai dari cek aplikasi, join komunitas, main, sampai pulang—apa sih yang paling ribet atau yang paling pengen kamu ubah jadi lebih gampang?" },
      { role: "user", content: "Hmmm." },
      { role: "agent", content: "Ambil waktu kamu, Farid. Nggak..." },
      { role: "user", content: "Tuh buktiin, join." },
      { role: "agent", content: "Ah oke, jadi yang paling ribet..." },
      { role: "user", content: "Join." },
      { role: "agent", content: "Ah oke, jadi yang paling ribet adalah proses join-nya ya? Bisa dijelasin lebih detail gimana maksudnya?" },
      { role: "user", content: "Jadi kalau misalnya mau rekrut tuh pembayar-- soalnya paling ribet pembayaran karena setiap join harus bayar di aplikasi lain lagi." },
      { role: "agent", content: "Ah oke, jadi yang paling ribet adalah pembayaran. Setiap kali kamu join latihan, kamu harus bayar di aplikasi lain lagi, bukan langsung di Reclub atau Kui. Itu memang agak merepotkan ya, harus bolak-balik aplikasi. Jadi kamu pengen semuanya bisa dalam satu aplikasi aja gitu?" },
      { role: "user", content: "Betul, coba bayar booking di aplikasi yang sama." },
      { role: "agent", content: "Ah oke, siap. Jadi idenya adalah bisa bayar langsung di aplikasi Reclub atau Kui yang sama, nggak perlu pindah-pindah aplikasi. Itu masuk akal banget. Nah, sekarang kita bahas tentang motivasi kamu. Jujur-jujuran aja, pasti ada hari-hari di mana kamu merasa malas atau mager. Apa yang bikin kamu tetap berangkat latihan di hari-hari seperti itu?" },
      { role: "user", content: "Kan emang udah rutinitas dan pengen ketemu temen-temen sih." },
      { role: "agent", content: "Ah oke, jadi rutinitas dan keinginan ketemu teman-teman yang bikin kamu tetap berangkat meski ada hari malas. Itu kuat banget motivasinya. Nah, motivasi kamu sekarang beda nggak sama waktu awal mulai main sofbol dulu? Sekarang lebih kejar apa dibanding dulu?" },
      { role: "user", content: "Sekarang sih lebih ke jernihkan skill dan persiapan ikut turnamen-turnamen besar." },
      { role: "agent", content: "Ah menarik! Jadi motivasi kamu berkembang dari awal. Dulu mungkin lebih sekadar fun dan sosialisasi, sekarang lebih fokus pada skill dan persiapan ikut turnamen besar. Itu bagus perkembangannya. Nah, seberapa penting buat kamu untuk jadi makin jago di sofbol? Dan biasanya kamu cari tips atau cara latihan dari mana? Misalnya YouTube, TikTok, coach, atau dari teman-teman?" },
      { role: "user", content: "Penting banget sih untuk improving biasanya lihat di YouTube sama ikut coaching." },
      { role: "agent", content: "Ah oke, jadi improving skill itu penting banget buat kamu. Kamu lihat YouTube dan juga ikut coaching. Itu bagus kombinasinya—belajar dari video dan juga dapat guidance langsung dari coach. Nah, menurutmu, apa sih arti \"komunitas\" di olahraga sofbol ini? Apakah cuma teman main atau lebih dari itu?" },
      { role: "user", content: "Itu tempat untuk punya teman-teman baru untuk mengasah skill, sharing knowledge, yang gitu-gitu sih." },
      { role: "agent", content: "Ah oke, jadi komunitas buat kamu adalah tempat punya teman baru, mengasah skill bareng-bareng, dan sharing knowledge. Itu lebih dari sekadar teman main ya. Nah, komunitas sofbol ini \"hidup\"-nya di mana sih? Lebih ramai pas ketemu langsung di lapangan atau di grup WhatsApp?" },
      { role: "user", content: "Boleh diulang?" },
      { role: "agent", content: "Iya, boleh. Jadi komunitas sofbol ini, di mana sih lebih ramai dan aktif? Apakah lebih di lapangan pas ketemu langsung, atau di grup WhatsApp?" },
      { role: "user", content: "Rame dua-duanya sih di grup WhatsApp juga rame, di lapangan juga seru." },
      { role: "agent", content: "Ah oke, jadi dua-duanya aktif dan rame—baik di grup WhatsApp maupun pas ketemu langsung di lapangan. Bagus banget. Nah, kamu tipe yang share hasil olahraga ke media sosial atau WhatsApp nggak, Farid? Misalnya share foto keringat, screenshot stats, atau video main?" },
      { role: "user", content: "Iya di-share ke Instagram video main terus hasil lemparan dan lain-lain. Oh iya nama saya Faris bukan Farid." },
      { role: "agent", content: "Ah maaf, Faris! Terima kasih sudah koreksi. Jadi kamu share ke Instagram video main, hasil lemparan, dan hal-hal lain gitu. Oke, kenapa kamu share itu? Reaksi atau pengakuan macam apa yang bikin kamu senang pas share?" },
      { role: "user", content: "Karena temen-temen pengen, pengen nunjukin ke temen-temen kalau misalnya aku udah mulai jago terus juga bisa share tips-tips atau share knowledge ke temen-temen." },
      { role: "agent", content: "Ah oke, jadi kamu share karena teman-teman pengen lihat, dan juga pengen nunjukin progress kamu—bahwa kamu udah mulai jago. Plus kamu juga bisa share tips dan knowledge ke teman-teman lewat share itu. Jadi ada dua hal—showing progress dan sharing knowledge. Nah, jadi buat kamu, yang lebih penting itu \"Achievement\"—pamer stats atau badges—atau \"Access\"—masuk sirkel gaul atau dapet info eksklusif dari komunitas?" },
      { role: "user", content: "Poin penting itu achievement bareng-bareng sih dan juga ngumpul sama temen-temennya." },
      { role: "agent", content: "Ah oke, jadi achievement bareng-bareng dan ngumpul sama teman-teman itu yang penting buat kamu. Itu bagus, Faris. Nah, aplikasi apa aja yang wajib ada di HP kamu buat dukung hobi sofbol ini? Misalnya Instagram, TikTok, Strava, WhatsApp, atau aplikasi lain?" },
      { role: "user", content: "Yang paling penting WhatsApp, Instagram, Kuy, Risk Club, YouTube, terus buat belanja." },
      { role: "agent", content: "Ah oke, jadi aplikasi yang wajib ada adalah WhatsApp, Instagram, Kuy, Reclub, YouTube, sama aplikasi belanja. Itu lumayan banyak ya. Nah, dari semua aplikasi itu, mana yang paling favorit dan paling sering kamu pakai buat dukung hobi sofbol kamu?" },
      { role: "user", content: "Kok idam, berikan." },
      { role: "agent", content: "Maaf Faris, bisa diulang? Kamu bilang apa tadi?" },
      { role: "user", content: "Kuis, kuis sama Riklan." },
      { role: "agent", content: "Ah oke, jadi Kuy dan Reclub yang paling sering kamu pakai. Nah, antara dua itu, mana sih yang paling favorit buat kamu?" },
      { role: "user", content: "Aku ini." },
      { role: "agent", content: "Maaf Faris, aku kurang jelas. Kamu pilih Kuy atau Reclub yang paling favorit?" },
      { role: "user", content: "Kuih." },
      { role: "agent", content: "Ah oke, jadi Kuy yang paling favorit. Siap. Nah, kamu tau aplikasi Kuy itu awalnya dari mana? Misalnya dari iklan, teman, atau gimana?" },
      { role: "user", content: "Dari komunitasnya yang share kalau misalnya untuk daftar via Kui." },
      { role: "agent", content: "Ah oke, jadi kamu tau Kuy dari komunitas sofbol yang share bahwa untuk daftar latihan harus via Kuy. Oke. Nah, apa satu hal yang bikin kamu akhirnya install aplikasi Kuy itu?" },
      { role: "user", content: "Kalau mau join Latina harus bayar di-- harus booking di Kui." },
      { role: "agent", content: "Ah oke, jadi karena untuk join latihan harus booking di Kuy, makanya kamu install. Itu praktis sih. Nah, apa kelebihan utama aplikasi Kuy ini dibanding aplikasi lain? Misalnya fiturnya, sosialnya, atau motivasinya?" },
      { role: "user", content: "Fiturnya kan jadwalnya banyak, orang-orang juga pada pakai dan untuk ngelihat siapa aja yang join lebih mudah." },
      { role: "agent", content: "Ah oke, jadi kelebihan Kuy adalah banyak jadwal latihan, orang-orang pada pakai, dan mudah lihat siapa aja yang join. Itu penting banget untuk komunitas ya. Nah, sekarang coba buka aplikasi Kuy di HP kamu. Bisa ceritain ke saya, tampilan atau fitur apa yang paling kamu suka di aplikasi itu?" },
      { role: "user", content: "Untuk cek history latihan, terus fitur untuk open di latihan." },
      { role: "agent", content: "Ah oke, jadi kamu suka fitur untuk cek history latihan dan fitur untuk open di latihan. Itu membantu banget ya buat tracking. Nah, sekarang yang jeleknya. Apa \"dosa terbesar\" atau hal paling nyebelin dari aplikasi Kuy ini?" },
      { role: "user", content: "Yang ini, Kang, ya." },
      { role: "agent", content: "Maaf Faris, aku kurang jelas. Bisa diulang apa yang paling nyebelin dari aplikasi Kuy?" },
      { role: "user", content: "Si Joe ini, si Joe ini enggak ada, Joe ini enggak ada." },
      { role: "agent", content: "Maaf Faris, aku masih kurang paham. Bisa dijelasin lebih detail apa yang enggak ada di aplikasi Kuy yang kamu maksud?" },
      { role: "user", content: "Kayaknya semua udah ada, jadi udah oke kok." },
      { role: "agent", content: "Ah oke, jadi sebenarnya semua fitur yang kamu butuhkan udah ada di Kuy dan kamu udah puas. Bagus. Nah, ada fitur di Kuy yang nggak pernah kamu sentuh sama sekali nggak?" },
      { role: "user", content: "Nggak, nggak." },
      { role: "agent", content: "Ah oke, jadi semua fitur kamu gunakan. Bagus. Nah, untuk urusan apa kamu malah tutup aplikasi Kuy dan pindah ke WhatsApp atau Instagram karena lebih gampang?" },
      { role: "user", content: "Halo, saya Kholiqan. Cuma buat bikin nol-nol orang kalau WhatsApp, Instagram, buat sosial medianya." },
      { role: "agent", content: "Ah oke, jadi kamu tutup Kuy dan pindah ke WhatsApp untuk komunikasi dengan orang-orang, dan Instagram buat social media. Itu masuk akal. Nah, kalau besok kamu jadi CEO aplikasi Kuy, satu hal apa yang mau kamu perbaiki atau tambahkan?" },
      { role: "user", content: "Hmmm, mungkin saja media." },
      { role: "agent", content: "Bisa dijelasin lebih detail, Faris? Maksudnya media apa yang mau kamu tambahkan?" },
      { role: "user", content: "Tapi bisa share, share progress, update, terus juga buat share foto-foto, jadi bisa orang-orang ngelihat accountku langsung tahu apa aja yang aku lakuin." },
      { role: "agent", content: "Ah oke, jadi kamu pengen ada fitur di Kuy buat share progress, update, dan foto-foto—semacam feed atau timeline gitu. Jadi orang-orang bisa langsung lihat di aplikasi Kuy apa aja yang kamu lakukan tanpa harus pindah ke Instagram. Itu ide bagus banget, Faris! Jadi lebih terintegrasi semua di satu tempat. Nah, waktunya sudah habis. Diskusi ini sangat membantu riset kami tentang kebiasaan olahraga dan penggunaan aplikasi. Ada lagi yang mau kamu sampaikan yang belum sempat kita bahas?" },
      { role: "user", content: "Hmmm, ada." },
      { role: "agent", content: "Oke, silakan Faris. Apa yang mau kamu sampaikan?" },
    ],
    audioUrl: "https://drive.google.com/file/d/1P-uwklSdPxT1oKdyk1z-fYoLSiiyujsW/view?usp=drive_link",
    keyInsights: [
      "Payment flow is fragmented - wants integrated booking & payment in one app",
      "Motivation evolved from fun to skill improvement & tournaments",
      "Community is key for both online (WhatsApp) and offline engagement",
      "Wants social features in Kuy to share progress & content",
    ],
  },
  {
    id: "02",
    name: "Anggun-01",
    tagline: "Multi-sport enthusiast - short session recording",
    demographics: {
      occupation: "Office Worker",
      sport: "Pilates, Yoga, Gym, Running, Squash",
      experience: "Several years",
      apps: ["Reclub", "Kuy", "WhatsApp", "Instagram"],
    },
    accentColor: "from-violet-500 to-purple-600",
    conversation: [
      { role: "agent", content: "Halo" },
      { role: "user", content: "Halo." },
      { role: "agent", content: "Halo! Selamat pagi. Terima kasih sudah meluangkan waktu untuk bergabung dengan saya hari ini. Nama saya Putri, dan saya akan memandu diskusi kita tentang kebiasaan olahraga kamu. Santai aja ya, nggak ada jawaban benar atau salah di sini. Boleh tahu nama kamu siapa dan apa kesibukan kamu sehari-hari?" },
      { role: "user", content: "Nama aku Anggun. Kesibukan kerja, hari-harinya kerja terus ngurus, eh, ya kerja aja sih sama olahraga di pagi, hari, dan weekend." },
      { role: "agent", content: "Ah oke, Anggun. Jadi kamu tipe yang bisa nyisipin olahraga di pagi hari dan juga weekend, meskipun kerja padat. Itu bagus banget. Udah berapa lama kamu menjalani hobi olahraga ini? Dan spesifiknya olahraga apa yang kamu lakuin?" },
      { role: "user", content: "Udah beberapa tahun belakangan olahraganya kalau pagi biasanya pilates atau yoga atau sempetin ke gym. Tapi kalau weekend bisa gym, bisa lari, bisa squash juga." },
      { role: "agent", content: "Ah menarik, jadi kamu tipe yang variatif banget ya—pagi ada pilates, yoga, atau gym, terus weekend bisa lari atau squash juga. Itu berarti olahraga itu udah jadi bagian penting dari rutinitas kamu. Gimana cara kamu bisa nyisipin semua itu di jadwal yang padat? Apakah jadwalnya ketat banget sampai ada hal lain yang terpaksa kamu korbankan biar tetap bisa olahraga?..." },
      { role: "user", content: "Udah beberapa tahun belakangan olahraganya kalau pagi biasanya pilates atau yoga atau sempetin ke gym. Tapi kalau weekend bisa gym, bisa lari, bisa squash juga." },
    ],
    audioUrl: "https://drive.google.com/file/d/1-DuYoh-P9-udVxKzzXUVMmGIJvX-cJ4-/view?usp=sharing",
    keyInsights: [
      "Multi-sport participant with varied routine",
      "Morning and weekend exercise schedule",
      "Short recording session - incomplete data",
    ],
  },
  {
    id: "03",
    name: "Anggun-02",
    tagline: "Squash player since 2017, uses Reclub for communities - full session",
    demographics: {
      occupation: "Office Worker",
      sport: "Squash, Pilates, Yoga, Gym, Running",
      experience: "Since 2017 (squash)",
      apps: ["Reclub", "Kuy", "WhatsApp", "Instagram"],
    },
    accentColor: "from-fuchsia-500 to-pink-600",
    conversation: [
      { role: "agent", content: "Halo" },
      { role: "user", content: "Halo." },
      { role: "agent", content: "Halo! Selamat..." },
      { role: "user", content: "Halo." },
      { role: "agent", content: "Halo! Selamat pagi. Terima kasih sudah meluangkan waktu untuk bergabung dengan saya hari ini. Nama saya Putri, dan saya akan memandu diskusi kita. Santai aja ya, nggak ada jawaban benar atau salah—ini cuma obrolan biasa. Boleh tahu nama kamu dan apa kesibukan sehari-hari kamu? Apa pekerjaan kamu?" },
      { role: "user", content: "Eh, namaku Anggun. Aku sehari-harinya, eh, kerja aja. Terus kalau misalnya lagi pengen olahraga, pagi-paginya olahraga atau biasanya weekend daripada bosen di rumah jadi olahraga juga pas weekend." },
      { role: "agent", content: "Ah menarik, Anggun! Jadi kamu kerja dan olahraga jadi cara kamu ngisi waktu luang, terutama di weekend. Oke, sebelum kita masuk lebih dalam, coba ceritain ke saya—udah berapa lama sih kamu menjalani hobi olahraga ini? Dan spesifiknya olahraga apa yang kamu suka?" },
      { role: "user", content: "Halo. Dulu berapa lamanya udah, eh, sebenarnya dari dulu suka dari sekolah udah suka olahraga. Tapi kalau kemarin kan pas kalau kerja kan pasti nggak selalu ada waktu. Jadi sempat stop tapi belakangan lagi mulai lagi, eh, pagi-pagi sebelum ke kantor coba buat gym atau pilates yang ada di dekat kantor. Terus kalau weekend bisa, eh, bisa lari, bisa gym juga lagi atau, eh, main squash." },
      { role: "agent", content: "Ah oke, jadi kamu udah lama suka olahraga sejak sekolah, tapi sempat berhenti pas kerja, dan sekarang lagi mulai lagi. Bagus banget! Jadi kamu sekarang main squash, gym, pilates, sama lari. Itu banyak banget aktivitas yang kamu lakukan. Nah, kita fokus dulu ke satu olahraga yang paling sering atau paling penting buat kamu sekarang. Dari squash, gym, pilates, sama lari—mana yang paling kamu lakuin atau paling kamu suka?" },
      { role: "user", content: "Hmmm, puas sekali ya." },
      { role: "agent", content: "Hehe, iya sih banyak pilihan! Tapi coba jawab dulu—dari semua itu, mana yang paling sering atau paling kamu suka sekarang?" },
      { role: "user", content: "Kuas." },
      { role: "agent", content: "Maaf, aku kurang..." },
      { role: "user", content: "Aku paling suka, aku paling suka kuas." },
      { role: "agent", content: "Ah, kuas? Maksudnya squash ya, Anggun? Oke, jadi squash yang paling kamu suka. Bagus! Nah, berapa lama sih kamu udah main squash ini?" },
      { role: "user", content: "Saya main squash mungkin udah dari 2002." },
      { role: "agent", content: "Wow, jadi udah 20-an tahun dong! Itu lama banget. Jadi squash beneran passion kamu sejak dulu. Oke, sekarang kita bahas gimana cara kamu nyisipkan waktu buat squash di jadwal kerja kamu yang sibuk. Gimana sih caranya kamu bisa tetap main squash sambil kerja?" },
      { role: "user", content: "Jadi kalau squash itu di weekend aja sih, di weekend, ee, Sabtu, seminggu sekali di hari Sabtu jam delapan atau jam sembilan pagi." },
      { role: "agent", content: "Ah oke, jadi seminggu sekali di hari Sabtu pagi, jam delapan atau sembilan. Itu konsisten banget! Nah, Anggun, apakah jadwalnya ketat gitu? Ada hal lain yang terpaksa kamu korbankan atau skip biar bisa main squash di hari Sabtu itu?" },
      { role: "user", content: "Um, masih kan masih pa-- paginya kan jadi kan biasanya memang pagi-pagi nggak terlalu banyak kegiatan jadi ya udah olahraga dulu pulang squash baru misalnya kegiatan lanjut kegiatan masak atau bersih rumah." },
      { role: "agent", content: "Ah oke, jadi pagi-pagi memang nggak terlalu banyak kegiatan, jadi kamu bisa olahraga dulu terus pulang baru lanjut ke kegiatan lain seperti masak atau bersih rumah. Itu fleksibel banget. Nah, sekarang coba kita balik ke masa lalu. Coba ingat-ingat dulu, pas pertama kali kamu mulai main squash—itu sekitar tahun 2002 kan. Apa momen atau pemicu yang bikin kamu mulai main squash? Siapa atau apa yang bikin kamu tertarik pertama kali?" },
      { role: "user", content: "Hmm, kayaknya pertama kali banget tuh kayaknya malah jauh dari itu lebih dulu deh 2017-an gitu pernah diajak kakak untuk nyoba main squash terus udah lama enggak baru 2023 eh 2022 baru ke ekspos lagi dan mulai main lagi." },
      { role: "agent", content: "Ah oke, jadi ceritanya gini—kakak kamu yang pertama kali ngajak nyoba main squash, tapi itu udah lama banget nggak main. Terus baru di tahun 2022-2023 kamu ke-ekspos lagi dan mulai main lagi. Itu menarik! Nah, coba ceritain—pas tahun 2022-2023 itu, apa yang bikin kamu tertarik lagi buat mulai main squash? Apa yang jadi pemicu atau momen \"Aha!\" kamu buat kembali main?" },
      { role: "user", content: "..." },
      { role: "agent", content: "..." },
      { role: "user", content: "Kayaknya waktu itu karena..." },
      { role: "agent", content: "Iya, lanjut aja. Apa yang jadi pemicunya?" },
      { role: "user", content: "Karena ada, em, apa namanya, lihat apa ya, saya sempat nyari-nyari olahraga-olahraga kan setelah pandemi terus di GBK. Ya udah cari aja yang main aman kan di GBK ada olahraga apa, terus inget pernah main squash dan itu menyenangkan, jadi ya udah pilih squash lagi aja." },
      { role: "agent", content: "Ah menarik! Jadi setelah pandemi, kamu nyari olahraga yang aman, terus kamu inget kalau dulu pernah main squash dan itu menyenangkan, jadi kamu pilih squash lagi. Itu masuk akal banget. Nah, begitu kamu memutuskan \"Oke, gue mau main squash lagi,\" apa satu hal pertama yang kamu lakukan? Apa yang kamu cari atau siapa yang kamu kontak pertama kali?" },
      { role: "user", content: "Pertama kali kayaknya nyari lapangannya dulu deh, nyari lapangannya dulu terus sebelumnya berarti sebelumnya aku lihatnya gara-gara temen aku juga ngeposting main squash jadi aku ngebook lapangannya di aplikasi di websitenya GBK tapi habis itu perlu coach jadi coachnya minta rekomendasi dari temen aku yang waktu itu aku lihat di Instagram pernah main squash." },
      { role: "agent", content: "Ah oke, jadi pertama kali kamu nyari lapangan, terus kamu lihat temen posting main squash di Instagram, terus kamu booking lapangan di website GBK. Terus setelah itu kamu butuh coach dan minta rekomendasi dari temen yang pernah main squash. Itu bagus banget—kamu pakai temen sebagai sumber informasi. Nah, waktu fase awal itu—pas kamu baru mulai lagi—apa tantangan atau kesulitan terbesar yang kamu hadapi? Ada yang ribet atau susah?" },
      { role: "user", content: "Oh pas itu sih sebenarnya lebih mungkin sebenarnya nyari temannya kali ya nyari temen yang banyak karena kan harganya juga lumayan waktu itu terus langsung dua jam. Jadi kalau kepikiran kalau emang cuma dua tiga orang kayaknya bakal capek banget. Jadi kayak nyari-nyari temen untuk ya minimal lima orang lah gitu." },
      { role: "agent", content: "Ah oke, jadi tantangan terbesar waktu itu adalah nyari temen yang mau main bareng. Karena harganya lumayan dan sesinya dua jam, jadi kamu pikir kalau cuma dua tiga orang bakal capek banget. Jadi kamu nyari minimal lima orang buat bagi-bagi biaya dan tenaga. Itu masuk akal banget. Nah, gimana caranya kamu nyari temen-temen itu? Dari mana aja kamu cari?" },
      { role: "user", content: "Hm, jadi ya udah tuh nyoba nyari eh temen, temen-temen main dulu aja sih kayak ah ah nggak, pokoknya kemarin kakak-kakak dulu, kakak-kakak kan udah di dua terus ajak saudara satu udah berempat. Jadi dari eh keluarga dulu baru besok-besokannya baru mulai ajak teman kantor, teman eh kumpul gitu." },
      { role: "agent", content: "Ah oke, jadi kamu mulai dari keluarga dulu—kakak-kakak terus saudara—jadi berempat. Terus baru setelah itu kamu ajak teman kantor dan teman kumpul. Itu strategi yang bagus, mulai dari yang terdekat dulu. Sekarang kita bahas rutinitas kamu yang sekarang. Coba bayangkan sesi squash kamu yang terakhir—pas kamu main squash terakhir kali itu. Apa yang jadi pemicu atau alasan kamu berangkat main squash hari itu? Apa jadwal rutin, atau ada notif dari temen, atau gimana?" },
      { role: "user", content: "Ehm, biasanya kan kalau belakangan emang selalu-- sejak pindah rumah jadinya kalau mainnya di, di Cibubur dan jam delapan atau jam sembilan tergantung coachnya available jam berapa. Nah terakhir tuh, ya udah lagi pengen olahraga aja, terus ya udah pengen squash dan enaknya kalau di Cibubur itu kan cuma satu jam dan harganya juga murah. Jadi kalau misalnya, eee, jadi lebih-- kalau aku private sendiri juga nggak apa-apa. Jadi ya udah waktu itu lagi pengen main, ehm, sendiri terus booking lapangan vers-- via coachnya ya udah sekalian ada coachnya deh mainnya." },
      { role: "agent", content: "Ah oke, jadi sekarang kamu main di Cibubur, jam delapan atau sembilan tergantung coach available. Terakhir kali kamu main, kamu lagi pengen olahraga aja, terus kamu pilih squash karena di Cibubur cuma satu jam dan harganya murah. Bahkan kamu bisa private sendiri juga nggak apa-apa. Terus kamu booking via coachnya dan sekalian ada coachnya. Oke, jadi prosesnya lebih simple sekarang. Nah, begitu kamu memutuskan \"Oke, gue mau main squash,\" apa langkah pertama yang kamu ambil? Apa yang kamu buka atau siapa yang kamu kontak pertama?" },
      { role: "user", content: "Hmmm, langsung ke posnya gitu sih, kan udah pernah punya nomor HPnya, eee, posnya jadi langsung..." },
      { role: "agent", content: "Ah oke, jadi kamu langsung hubungi coach via nomor HP yang udah kamu punya. Terus gimana prosesnya setelah itu? Kamu bilang apa ke coach, terus coach ngapain?" },
      { role: "user", content: "Ya cuma tinggal bilang aja sih Coach mau main hari Sabtu seperti biasa jam delapan. Terus ternyata dia bilangnya, oh biasanya jam sembilan. Oh ya udah jadi jam sembilan." },
      { role: "agent", content: "Ah oke, jadi kamu tinggal bilang ke coach \"Mau main hari Sabtu jam delapan seperti biasa,\" terus coach bilang biasanya jam sembilan, jadi kamu agree jam sembilan. Simple banget prosesnya. Nah, pas kamu lagi main squash, fokus utama kamu apa sih? Kamu lebih kejar performa atau tracking hasil, atau lebih sekedar have fun dan sosial aja sama temen atau coach?" },
      { role: "user", content: "Kalau dikasih tahu, soalnya sih karena emang itu lagi nyarinya untuk melamiskan energi gitu kan. Jadi kayak ya udah main main main santai aja, gak terlalu ngetrek performa atau gimana gimana sih." },
      { role: "agent", content: "Ah oke, jadi kamu main squash lebih untuk ngeluarin energi dan santai aja, nggak terlalu ngetrek performa. Itu bagus banget—lebih fokus ke fun dan relaksasi. Nah, pas kamu lagi main, ada aplikasi yang nyala nggak? Kayak Strava atau aplikasi tracking lainnya, atau nggak ada?" },
      { role: "user", content: "Hmmm, ada-- enggak terlalu, enggak terlalu ngetrekin gimana sih, padahal sih pakai smartwatch, tapi itu biasanya buat ngecekin kalori di akhir. Itu pun juga sebenarnya enggak terlalu dilihatin banget, cuma pengen apa namanya, eee, buat selain fungsi jam aja." },
      { role: "agent", content: "Ah oke, jadi kamu pakai smartwatch tapi nggak terlalu ngetrek performa. Cuma di akhir kamu cek kalori, tapi juga nggak terlalu diperhatiin. Smartwatch-nya lebih buat fungsi jam aja. Paham. Nah, detik di mana kamu berhenti main squash, apa hal pertama yang kamu lakukan? Cek stats, mandi, cari makan, atau apa?" },
      { role: "user", content: "Hmm, pertama pasti kan udah apa cooling down, terus minum dulu, santai dulu, baru biasanya lihat udah tadi jadinya mainnya berapa lama, terus heart rate nya gimana, terus kalorinya berapa, habis itu mulai nyari pulangnya mau naik apa. Terus kalau misalnya kalau laper, oh ternyata kemarin lagi laper tuh, ya udah sekalian makan gimana ya atau mau beli makan apa buat dibawa pulang." },
      { role: "agent", content: "Ah oke, jadi setelah main kamu cooling down dulu, minum, santai. Terus kamu lihat berapa lama main, heart rate, sama kalori. Terus kamu pikirin mau naik apa buat pulang, dan kalau laper kamu cari makan atau beli buat dibawa pulang. Itu lengkap banget prosesnya. Nah, dari semua proses tadi—dari booking sampai pulang—apa sih yang paling ribet atau yang paling pengen kamu ubah jadi lebih gampang?" },
      { role: "user", content: "Hmmm. Jadi sebenarnya atau mungkin rekomendasi makanan kali ya. Jadi kalau misalnya kita habis olahraga, direkomendasi makanan-makanan jenis seperti apa yang cocok habis olahraga itu gitu." },
      { role: "agent", content: "Ah menarik! Jadi kamu pengen ada rekomendasi makanan yang cocok habis olahraga. Itu berguna banget, terutama pas kamu lagi laper setelah main squash. Nah, sekarang kita bahas motivasi kamu. Jujur-jujuran aja, pasti ada hari malas (mager) kan. Apa yang bikin kamu tetap berangkat main squash di hari-hari seperti itu?" },
      { role: "user", content: "Hmmm. Biasanya komitmen sih kalau, kalau terutama buat hal-hal karena aku biasanya lebih banyak private atau kelas. Jadi mungkin komitmen karena sudah booking itu yang membuat aku walaupun capek tetap di eeeh, paksa lah buat datang gitu karena udah keburu bayar atau udah keburu booking kelas." },
      { role: "agent", content: "Ah oke, jadi komitmen yang udah kamu buat—karena udah booking dan udah bayar—itu yang bikin kamu tetap datang meskipun capek atau mager. Itu strong motivator banget. Nah, motivasi kamu sekarang beda nggak sama waktu awal mulai main squash lagi? Dulu waktu 2022-2023 kamu mulai lagi, motivasinya apa? Sekarang motivasinya berubah jadi apa?" },
      { role: "user", content: "Hmmm. Kalau dari dulu gitu kan, kalau mau tipe sih udah mau balik ke olahraga aja, apa ya yang fun bareng-bareng gitu. Kalau sekarang karena lebih banyaknya main sendiri ya lebih ke arah, ehm, ya udah main lagi pengen main apa dan ngeluarin energinya gimana gitu." },
      { role: "agent", content: "Ah oke, jadi dulu waktu mulai lagi motivasinya lebih ke fun bareng-bareng, tapi sekarang karena lebih banyak main sendiri, motivasinya lebih ke ngeluarin energi dan santai aja. Berubah sih tapi masih tetap tentang olahraga dan fun. Nah, seberapa penting buat kamu untuk jadi makin jago main squash? Kamu pengen improve skill atau nggak terlalu?" },
      { role: "user", content: "Mungkin prosesnya pasti sih sebenarnya kalau ehm that's why juga kalau lebih banyaknya kita private gitu biar enggak terlalu apa ya biar enggak terlalu dependen ke orang untuk progresnya. Jadi kalau private kan ya udah kita lagi kita lagi lagi kondisi fit ya kita bisa ngejar nih dalam belajarnya. Tapi kalau lagi enggak terlalu yang gimana lagi enggak terlalu fit ya santai aja. Jadi lebih kayak fleksibelnya di situ. Sama ehm sama buat ya buat mainnya sih at the end kita bakal main sama coach kan. Jadi kayak improve ehm mainnya dan terutama mungkin lebih ke stamina kali ya. Jadi-Kayak ehm yang aku tau biasanya tuh aku lihatinnya lebih kayak oh latihan kali ini aku enggak terlalu ngep daripada latihan sebelumnya gitu." },
      { role: "agent", content: "Ah oke, jadi kamu pengen improve tapi dengan cara yang fleksibel. Dengan private kamu nggak terlalu dependen ke orang lain, bisa adjust sesuai kondisi fit kamu. Terus fokusnya lebih ke stamina dan improvement yang kamu lihat dari latihan ke latihan. Itu masuk akal banget. Nah, biasanya kamu cari tips atau cara latihan dari mana? Dari coach, YouTube, TikTok, atau dari mana?" },
      { role: "user", content: "Hmmm. Benernya dari Coach sih karena Coach kan yang sering yang ngelihat kita main gitu. Jadi apa yang perlu difokusin di improve dari gaya main kita gitu. Tapi habis itu juga suka ngelihat video-video tapi enggak sampai YouTube sih biasanya kayak cuma TikTok yang sebentar-sebentar aja." },
      { role: "agent", content: "Ah oke, jadi sumber utama kamu adalah Coach karena dia yang lihat langsung gimana kamu main dan apa yang perlu improve. Terus kamu juga lihat video di TikTok sebentar-sebentar. Itu kombinasi yang bagus. Nah, menurutmu, apa sih arti \"komunitas\" di olahraga squash ini? Apa cuma teman main atau lebih dari itu?" },
      { role: "user", content: "Kalau komunitas, mungkin teman-teman main sih biasanya. Lebih karena biasanya komunitas juga aku ikutnya yang mabar-mabar jarang yang apa namanya jarang yang coaching. Jadi emang buat main aja." },
      { role: "agent", content: "Ah oke, jadi buat kamu komunitas di squash itu lebih ke teman-teman main, bukan yang coaching. Kamu ikut komunitas yang mabar-mabar aja. Nah, komunitas ini \"hidup\"-nya di mana sih? Lebih ramai pas ketemu langsung atau di Grup WhatsApp atau media sosial?" },
      { role: "user", content: "Hm, kalau komunitas biasanya ikut dari aplikasi aja sih. Aku biasa ikut aplikasi Reklab dan kawan-kawan." },
      { role: "agent", content: "Ah oke, jadi kamu ikut komunitas squash lewat aplikasi Reklab. Nah, di aplikasi Reklab itu, lebih ramai pas ketemu langsung saat main atau lebih aktif di dalam aplikasinya?" },
      { role: "user", content: "Emm, yang pasti lebih aktif pas ketemu langsung sih. Karena pas kasih online kan emang cuma untuk masalah booking dan pembayaran aja." },
      { role: "agent", content: "Ah oke, jadi di Reklab lebih aktif pas ketemu langsung, sedangkan online cuma buat booking dan pembayaran aja. Paham. Nah, kamu tipe yang share hasil olahraga ke Instagram atau WhatsApp nggak? Biasanya share apa—foto keringat, screenshot stats, atau apa?" },
      { role: "user", content: "Ya, enggak ada yang nggak ada yang tapi lumayan sering tapi biasanya lebih kayak video misalnya video pas lagi main atau video pas main sambil sekalian nge-share, emm, olahraganya berapa lama, kalorinya ke berapa gitu." },
      { role: "agent", content: "Ah oke, jadi kamu share video pas lagi main atau setelah main, terus share juga berapa lama main dan kalorinya berapa. Itu bagus banget. Nah, kenapa kamu share itu? Apa yang bikin senang atau apa reaksi yang kamu harapkan dari orang lain?" },
      { role: "user", content: "Eee, sebenarnya lebih kayak, karena kan, eee, beberapa temen aku main squash juga. Jadi buat kayak, \"Eh, kamu main squash nih?\" gitu. Tapi lebih dari itu, lebih kayak buat nge-share, eee, improvement aku main aja sih. Sebenarnya bukan, bukan buat terlalu dilihat banget. Soalnya biasanya aku, karena memang aku selalu ngerekam pas aku main. Aku ngerekam main tuh supaya bisa tahu, oh, eee, kali ini tadi harusnya poinnya harusnya kayak gini. Oh, langkahnya harusnya kayak gini, gitu. Jadi lebih kayak buat self improvement. Tapi karena daripada banyak video di HP, jadi berapa kali aku keluarin. Jadi in-- eee, biar yang di HP bisa aku bu-- delete nanti, eee...Apa namanya, eee, kalau mau lihat-lihat lagi yang dari sos-- dari IG-nya gitu." },
      { role: "agent", content: "Ah oke, jadi sebenarnya kamu share video lebih buat self improvement—kamu ngerekam buat lihat kembali gimana performa kamu, apa yang perlu diperbaiki. Terus kamu share ke Instagram juga biar bisa delete dari HP dan bisa lihat lagi nanti kalau butuh. Itu smart banget—dokumentasi sekaligus self-reflection. Jadi buat kamu, yang lebih penting itu achievement—kayak pamer stats atau improvement—atau lebih ke access, kayak masuk sirkel gaul atau dapet info eksklusif?" },
      { role: "user", content: "Ini pertanyaannya." },
      { role: "agent", content: "Iya, jadi buat kamu yang lebih penting itu apa—achievement (pamer stats, improvement, badges) atau access (masuk sirkel gaul, dapet info eksklusif)?" },
      { role: "user", content: "Hmmm, lebih ke sih, men, soalnya sih, men, kayak sih, buat nge-check, eee, kita tahu, kita udah sampai jauh, mana kita improve dari berapa latihan gitu." },
      { role: "agent", content: "Ah oke, jadi lebih ke achievement—kamu pengen tahu kamu udah sampai jauh mana dan gimana improvement kamu dari latihan ke latihan. Itu masuk akal banget. Nah, aplikasi apa aja yang wajib ada di HP kamu buat dukung hobi squash ini? Reklab pasti ada, terus apa lagi—Instagram, TikTok, WhatsApp, atau apa?" },
      { role: "user", content: "Hmmm, kalau buat squash doang, kayaknya, eee, itu sama, eee, Reclab, terus ada KUI juga, arau sama WhatsApp sih paling, karena kan kalau yang diii, apa, kalau buat private biasanya lebih banyaknya pakai WhatsApp untuk, eee, coach-nya. Oh, sama Instagram buat tahu jadwal, biasanya." },
      { role: "agent", content: "Ah oke, jadi aplikasi yang wajib ada itu Reklab, KUI, WhatsApp buat komunikasi sama coach, sama Instagram buat tahu jadwal. Itu lengkap banget. Nah, sekarang kita bedah satu aplikasi favorit kamu. Dari semua aplikasi tadi—Reklab, KUI, WhatsApp, Instagram—mana yang paling favorit dan paling sering kamu pakai buat squash?" },
      { role: "user", content: "Hmmm, WhatsApp sih." },
      { role: "agent", content: "Ah oke, WhatsApp yang paling sering. Tapi itu lebih buat komunikasi sama coach ya. Nah, kalau dari aplikasi yang khusus buat squash atau olahraga—antara Reklab sama KUI—mana yang lebih sering kamu pakai?" },
      { role: "user", content: "eclap." },
      { role: "agent", content: "Maaf, aku kurang dengar. Reklab atau KUI? Mana yang lebih sering?" },
      { role: "user", content: "Reclap." },
      { role: "agent", content: "Ah, Reklab ya? Oke, jadi Reklab yang paling sering kamu pakai. Bagus. Nah, kamu tau Reklab itu awalnya dari mana? Dari iklan, temen, atau gimana kamu tau aplikasi itu?" },
      { role: "user", content: "Dari kayak komunitas deh, jadi kayak tahu, oh kalau karena sempat lihat teman ngepost dia main squash terus lihat dia ikut komunitas dan ternyata buat ikut komunitas itu harus joinnya dari daftarnya harus dari klub gitu, jadi install klub waktu itu." },
      { role: "agent", content: "Ah oke, jadi kamu tau Reklab dari temen yang ngepost main squash, terus kamu lihat dia ikut komunitas, dan ternyata buat join komunitas harus daftar dari klub, jadi kamu install Reklab waktu itu. Itu organic banget—dari temen. Nah, apa satu hal yang bikin kamu akhirnya install dan pakai Reklab? Apa yang jadi \"hook\"-nya?" },
      { role: "user", content: "..." },
      { role: "agent", content: "Apa yang bikin..." },
      { role: "user", content: "Oh ya, kalau." },
      { role: "agent", content: "Iya, lanjut..." },
      { role: "user", content: "Ya, ya karena ada, karena komunitas itu adanya bisa bookingnya dari RecLab itu." },
      { role: "agent", content: "Ah oke, jadi hook-nya adalah karena bisa booking langsung dari Reklab. Itu praktis banget—satu aplikasi buat semua. Nah, apa kelebihan utama Reklab dibanding aplikasi lain? Apa yang bikin Reklab lebih bagus—fiturnya, sosialnya, atau apa?" },
      { role: "user", content: "Mungkin pilihan apa, pilihan komunitas lebih banyak di RecLab ya. Komunitas-komunitas banyaknya pakai RecLab memang. Terus secara experience di aplikasi juga lebih mudah, lebih jelas, lebih gampang untuk nemuin komunitas apa aja yang ada di masing-masing olahraga yang pengen kita coba gitu. Terus proses untuk komunikasi, pembayaran juga lebih mudah di RecLab." },
      { role: "agent", content: "Ah oke, jadi kelebihan Reklab itu banyak pilihan komunitas, experience aplikasinya lebih mudah dan jelas, gampang nemuin komunitas, terus komunikasi dan pembayaran juga lebih mudah. Itu comprehensive banget. Nah, coba buka aplikasi Reklab di HP kamu sekarang. Ceritain ke saya, tampilan apa yang paling kamu suka di situ? Apa yang paling eye-catching atau yang paling sering kamu lihat?" },
      { role: "user", content: "Hmmm." },
      { role: "agent", content: "Coba buka..." },
      { role: "user", content: "Yang paling..." },
      { role: "agent", content: "Iya, lanjut. Apa yang paling kamu suka dari tampilannya?" },
      { role: "user", content: "Yang paling ku suka sebenarnya, ehm, itu pilihan, jadi pilihan apa, eh, komunitas yang paling sering kita, eh, join tuh di paling depan. Jadi lebih gampang buat, eh, milih komunitas yang udah pernah kita mainin. Karena biasanya kan kita ngulang-ngulang aja sebenarnya komunitas." },
      { role: "agent", content: "Ah oke, jadi yang paling kamu suka itu komunitas yang paling sering kamu join ditampilin di paling depan. Itu convenient banget—nggak perlu scroll-scroll buat cari komunitas yang udah familiar. Nah, sekarang yang jeleknya. Apa \"dosa terbesar\" atau hal paling nyebelin dari Reklab?" },
      { role: "user", content: "RecLab tuh sering banget ke logout. Sedangkan aku tuh suka lupa passwordnya. Jadi harus bolak-balik forgot password dan recover password gitu." },
      { role: "agent", content: "Ah oke, jadi Reklab sering logout sendiri, terus kamu suka lupa password, jadi harus bolak-balik forgot password dan recover password. Itu frustrating banget, apalagi kalau kamu lagi pengen cepat-cepat booking. Ada fitur lain yang nggak pernah kamu sentuh sama sekali di Reklab? Fitur apa yang kamu nggak pernah pakai?" },
      { role: "user", content: "Hmmm, enggak sih kalau fitur lainnya kan sering pakai, pakai-pakai aja kayak misalnya apa ngasih eh appraisal ke yang lain gitu-gitu masih pakai sih." },
      { role: "agent", content: "Ah oke, jadi kamu pakai hampir semua fitur, termasuk appraisal ke orang lain. Itu bagus—kamu explore fitur-fiturnya. Nah, untuk urusan apa kamu malah tutup Reklab dan pindah ke WhatsApp atau Instagram karena lebih gampang?" },
      { role: "user", content: "Begitu dengan komunitasnya sih, kalau misalnya emang aku lagi pengen join komunitas emang banyaknya di Reclap. Tapi kalau buat yang aku pengen booking pribadi, private itu biasanya dari WhatsApp." },
      { role: "agent", content: "Ah oke, jadi Reklab kamu pakai buat join komunitas, tapi kalau mau booking private kamu lebih pakai WhatsApp langsung sama coach. Itu makes sense—WhatsApp lebih personal dan direct. Nah, kalau besok kamu jadi CEO Reklab, satu hal apa yang mau kamu perbaiki atau tambahkan?" },
      { role: "user", content: "Hmmm... Mungkin sistem eeeh, kayak cross sell olahraga cabang cabang olahraga lain kali ya. Jadi misalkan aku baca kemarin mainnya squash tapi misal diajakin main pilates gitu." },
      { role: "agent", content: "Ah menarik! Jadi kamu pengen ada sistem cross-sell atau rekomendasi olahraga lain berdasarkan apa yang udah kamu mainkan. Kayak \"Kamu main squash, mungkin kamu juga suka pilates\" gitu. Itu bisa bikin user explore olahraga baru dan komunitas baru. Bagus banget idenya! Nah Anggun, waktunya sudah habis. Diskusi ini sangat membantu riset kami. Ada lagi yang mau disampaikan yang belum sempat kita bahas?" },
      { role: "user", content: "Sudah itu aja. Sudah itu aja." },
      { role: "agent", content: "Oke, terima kasih banyak Anggun atas waktunya. Diskusi kita hari ini sangat berharga dan membantu banget buat riset kami. Saya appreciate banget kamu udah berbagi pengalaman dan insight tentang squash dan Reklab. Sehat selalu dan selamat terus beraktivitas olahraga ya!" },
      { role: "user", content: "Oke." },
      { role: "agent", content: "Terima kasih..." },
      { role: "user", content: "Terima kasih." },
      { role: "agent", content: "Sama-sama, Anggun! Sampai jumpa lagi ya. Sehat selalu!" },
    ],
    audioUrl: "https://drive.google.com/file/d/1vP26ooohzxvHnCz_RbNEl8g6OYRUV-Cu/view?usp=drive_link",
    keyInsights: [
      "Finding enough people to share costs is a major friction point",
      "Uses recording for self-improvement, not social validation",
      "Frequent logout issues cause frustration with Reclub",
      "Wants cross-sport recommendations to discover new activities",
    ],
  },
]
